name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32h7_b0_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32h7_b0_dc = { path = ".." }

[configuration.values]
stm32h7_b0_dc.Device = "stm32h7b0abi6q"
stm32h7_b0_dc.Boot_Memory = "itcm"
