name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32l1_51_52_62_c_d_e_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32l1_51_52_62_c_d_e_dc = { path = ".." }

[configuration.values]
stm32l1_51_52_62_c_d_e_dc.Device = "stm32l151cct6"
stm32l1_51_52_62_c_d_e_dc.Boot_Memory = "flash"
