name = "stm32h7_23_33_dc"
description = "Device configuration for stm32h7_23_33_dc micro-controllers"
version = "0.1.0-dev"
authors = ["a script"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
[configuration.variables]
Device = {type = "Enum", values = ["stm32h723veh6", "stm32h723vet6", "stm32h723vgh6", "stm32h723vgt6", "stm32h723zei6", "stm32h723zet6", "stm32h723zgi6", "stm32h723zgt6", "stm32h733vgh6", "stm32h733vgt6", "stm32h733zgi6", "stm32h733zgt6"]}
Boot_Memory = {type = "Enum", values = ["d2_sram2", "dtcm", "itcm", "d1_sram", "d2_sram1", "flash", "backup", "d3_sram"]}
Stack_Size = {type = "Integer", first = 1, default = 1024}
