name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
nrf52811_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
nrf52811_dc = { path = ".." }

[configuration.values]
nrf52811_dc.Device = "nrf52811-xxaa"
nrf52811_dc.Boot_Memory = "flash"
