name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32f4_01_11_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32f4_01_11_dc = { path = ".." }

[configuration.values]
stm32f4_01_11_dc.Device = "stm32f401cbu3"
stm32f4_01_11_dc.Boot_Memory = "flash"
