name = "samg54_dc"
description = "Device configuration for samg54_dc micro-controllers"
version = "0.1.0-dev"
authors = ["a script"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
[configuration.variables]
Device = {type = "Enum", values = ["samg54g19-xx", "samg54j19-mu", "samg54n19-au"]}
Boot_Memory = {type = "Enum", values = ["ram", "flash"]}
Stack_Size = {type = "Integer", first = 1, default = 1024}
