name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
samd21_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
samd21_dc = { path = ".." }

[configuration.values]
samd21_dc.Device = "samd21e15a-af"
samd21_dc.Boot_Memory = "flash"
