name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32g4_73_83_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32g4_73_83_dc = { path = ".." }

[configuration.values]
stm32g4_73_83_dc.Device = "stm32g473cbt3"
stm32g4_73_83_dc.Boot_Memory = "flash"
