name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
samd51_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
samd51_dc = { path = ".." }

[configuration.values]
samd51_dc.Device = "samd51g18a-mf"
samd51_dc.Boot_Memory = "flash"
