name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32wb_35_55_5m_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32wb_35_55_5m_dc = { path = ".." }

[configuration.values]
stm32wb_35_55_5m_dc.Device = "stm32wb35ccu6a"
stm32wb_35_55_5m_dc.Boot_Memory = "flash"
