name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32f1_00_4_6_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32f1_00_4_6_dc = { path = ".." }

[configuration.values]
stm32f1_00_4_6_dc.Device = "stm32f100c4t6"
stm32f1_00_4_6_dc.Boot_Memory = "flash"
