name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
samg51_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
samg51_dc = { path = ".." }

[configuration.values]
samg51_dc.Device = "samg51g18-xx"
samg51_dc.Boot_Memory = "flash"
