name = "stm32f1_03_8_b_dc"
description = "Device configuration for stm32f1_03_8_b_dc micro-controllers"
version = "0.1.0-dev"
authors = ["a script"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
[configuration.variables]
Device = {type = "Enum", values = ["stm32f103c8t6", "stm32f103c8t7", "stm32f103cbt6", "stm32f103cbt7", "stm32f103cbu6", "stm32f103cbu7", "stm32f103r8h6", "stm32f103r8h7", "stm32f103r8t6", "stm32f103r8t7", "stm32f103rbh6", "stm32f103rbh7", "stm32f103rbt6", "stm32f103rbt7", "stm32f103t8u6", "stm32f103t8u7", "stm32f103tbu6", "stm32f103tbu7", "stm32f103v8h6", "stm32f103v8t6", "stm32f103vbh6", "stm32f103vbh7", "stm32f103vbi6", "stm32f103vbi7", "stm32f103vbt6", "stm32f103vbt7"]}
Boot_Memory = {type = "Enum", values = ["sram1", "flash"]}
Stack_Size = {type = "Integer", first = 1, default = 1024}
