name = "example"
description = "Shiny new project"
version = "0.1.0-dev"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <fabien.chouteau@gmail.com>"]
maintainers-logins = ["Fabien-Chouteau"]

executables = ["example"]
[[depends-on]]
stm32wb_30_50_dc = "*"
gnat_arm_elf = ">=12"

[[pins]]
stm32wb_30_50_dc = { path = ".." }

[configuration.values]
stm32wb_30_50_dc.Device = "stm32wb30ceu6a"
stm32wb_30_50_dc.Boot_Memory = "flash"
